name = "analyzer"
main = "src/index.ts"
compatibility_date = "2024-02-22"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "prod-d1-analyzer"
database_id = "5a551be7-a73d-4290-8925-dd0553cbf7d1"
